version: "3.7"
services:
        nginx:
                container_name: nginx
                image: nginx:latest
                volumes:
                        - type: bind
                          source: ./nginx/nginx.conf
                          target: /etc/nginx/nginx.conf
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
                depends_on:
                        - projectreflectionfront
                        - projectreflectionfacade
                        - projectreflectionform
                        - projectreflectionconsumer
        activemq:
                container_name: activeq
                image: webcenter/activemq:latest
        mongodb:
                container_name: mongodb
                image: mongo
        sonarqube:
                container_name: sonarqube
                image: sonarqube
        jenkins:
                container_name: jenkins
                image: bobcrutchley/jenkins:latest
                ports:
                        - target: 8080
                          published: 8080
                          protocol: tcp
                volumes:
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
        projectreflectionfront:
                container_name: projectreflectionfront
                image: projectreflectionfront:latest
                ports:
                        - target: 3000
                          published: 3000
                          protocol: tcp
        projectreflectionfacade:
                container_name: projectreflectionfacade
                image: projectreflectionfacade:latest
                ports:
                        - target: 8081
                          published: 8081
                          protocol: tcp
        projectreflectionform:
               container_name: projectreflectionform
               image: projectreflectionform:latest
               ports: 
                        - target: 8082
                          published: 8082
                          protocol: tcp
        projectreflectionconsumer:
                container_name: projectreflectionconsumer
                image: projectreflectionconsumer:latest
                ports: 
                        - target: 8084
                          published: 8084
                          protocol: tcp        
        projectreflectiondbreader:
                container_name: projectreflectiondbreader
                image: projectreflectiondbreader:latest
                ports:
                        - target: 8085
                          published: 8085
                          protocol: tcp

